# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fdaffba02d68e2aa8c3d1d6da96093c1be61fcb28e91fabfe8ead40ca260adcbcf1a75a6ed407edb119a5306b38a9e80093fdf95e755668f61cee28913ac56a9

test:
  secret_key_base: d2dd94fbfc122434af6bfe161ea93045363845aa364aaeccca89044bcd865c9ea7f5444353ed3d77c71ef31eabbe13556c419d057cc54ac9ffac196ebdaf0182

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
